// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2RcxmaqDLpy5kIcNCDWTsU2gqKjdJvNU',
    appId: '1:1051096948940:web:5f942fddf503a34edf6269',
    messagingSenderId: '1051096948940',
    projectId: 'project-n2-ca818',
    authDomain: 'project-n2-ca818.firebaseapp.com',
    storageBucket: 'project-n2-ca818.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1DoyC9iSOnCZqjBmhKvy1iLnCBqyM7X0',
    appId: '1:1051096948940:android:6884e7ec0832920ddf6269',
    messagingSenderId: '1051096948940',
    projectId: 'project-n2-ca818',
    storageBucket: 'project-n2-ca818.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpYS4vR2aW2oiONDATDQKOzXKboNa5lN8',
    appId: '1:1051096948940:ios:6336f943a4df1832df6269',
    messagingSenderId: '1051096948940',
    projectId: 'project-n2-ca818',
    storageBucket: 'project-n2-ca818.appspot.com',
    iosClientId: '1051096948940-41sjmjhgqgnlpvfrhacaclivtgkpujh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectN2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpYS4vR2aW2oiONDATDQKOzXKboNa5lN8',
    appId: '1:1051096948940:ios:6336f943a4df1832df6269',
    messagingSenderId: '1051096948940',
    projectId: 'project-n2-ca818',
    storageBucket: 'project-n2-ca818.appspot.com',
    iosClientId: '1051096948940-41sjmjhgqgnlpvfrhacaclivtgkpujh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectN2',
  );
}
